### ISSUE TITLE
Question about the results of your simulation script

### ISSUE THREAD

**Issue by antoine186** [friend1ws/pmsignature#30]
Hello,

In your simulation script, which can be found on your pmsignature_paper repo (https://github.com/friend1ws/pmsignature_paper/blob/master/analysis/simulation/script/subscript/repeatSimulation.R), you produce a few results, which I do not but would very much like to understand:

For one, what are Dists columns meant to represent? Why are there 4 of them?

Secondly, in your G_sim list, why does the featureVectorList change in column length as we change the number of mutations? Additionally, is this vector one that counts the number of mutation types?

Thirdly, bgprob are a set of probabilities for the background relating to each possible mutation signature. Is my understanding correct? So to get the actual background mutation counts, we should just multiply bgprob to a total number of counts?

Thanks.

**Comment by antoine186** [comment]
Sorry, I need to add an additional sub-question: what is the difference between countData in G_sim and featureVectorList?

**Comment by antoine186** [comment]
Final additional question: in G_sim, is it possible to turn featureVectorList into a simple count for each mutational signature? so instead of it being 3 * N dimensions, could it be 1 * N dimensions? How would I do that? I know all three features are independent from each other, but I don't know if I should add or multiply?

**Comment by zhiiiyang** [comment]
Hi, I am pretty familiar with pmsignature via using it for my work. I hope I can answer those questions for you. 

**- For one, what are Dists columns meant to represent? Why are there 4 of them?**

Since you specified the background signature to be true, pmsignature will only return four (5 - 1 BG) signatures. In each iteration, it computes the cosine similarities between the real signatures, G_sim[[2]], and the estimated signatures, Param_est@signatureFeatureDistribution, and store them in the data frame Dists. 

**- Secondly, in your G_sim list, why does the featureVectorList change in column length as we change the number of mutations? Additionally, is this vector one that counts the number of mutation types?**

The featureVectorList is generated probabilistically under the mixed membership model in pmsignature (see the illustration below on how a mutation is generated). You can read more details from the paper. In summary, not only the column length of the featureVectorList changes by different numbers of mutations but also might be subject to changes even with the exact same arguments but a different seed number. And you are right about the column length is the total number of mutation types. 

![image](https://user-images.githubusercontent.com/7269113/60410239-29bccd80-9b7c-11e9-8a34-dd1bcb0fbb03.png)

**-Thirdly, bgprob are a set of probabilities for the background relating to each possible mutation signature. Is my understanding correct? So to get the actual background mutation counts, we should just multiply bgprob to a total number of counts?**

Here is the quote from the paper. 
Background signatures
Here, we describe how the background mutation signature is obtained in the case where mutation features are the substitution patterns, the ±2 flanking bases, and the transcription strand. Since the majority of the data used in this paper is exome sequencing data, and since we consider transcription strand as a mutation feature, we use the exonic regions of the human genome reference sequence to obtain the background mutation signature. First we calculate the frequencies of 5-mers with transcription strands of the corresponding exon, where we take complement sequences and flip the strand for those whose central bases are A or G. Then, assuming alternated bases are equally likely from each central base C and T, the frequency of each mutation feature is derived directly from those of the 5-mers and transcription strands. Finally, the probability of each mutation feature is derived by normalizing each frequency to sum to one.

**-what is the difference between countData in G_sim and featureVectorList**

featureVectorList is an exhaustive list of all mutation types while countData is a summary of frequencies of each mutation types across samples. 

**-in G_sim, is it possible to turn featureVectorList into a simple count for each mutational signature? so instead of it being 3 * N dimensions, could it be 1 * N dimensions? How would I do that? I know all three features are independent from each other, but I don't know if I should add or multiply?**

I don't think that I fully understand your question about turning featureVectorList into a simple count for each mutational signature. You can access the probabilistic distribution of each signature from G_sim[[2]]. The assignment of each mutation to mutational signature is latent which is not observable from the real data or through computation.

**Comment by antoine186** [comment]
Thanks a lot, your answer is really clear and helpful!

**Comment by antoine186** [comment]
I do have a follow up question @zhiiiyang. You mention that: 'Since you specified the background signature to be true, pmsignature will only return four (5 - 1 BG) signatures'. 
I would expect it to return the exact specified number of signatures, not (5 - 1 BG)... Therefore, why is it returning (5 - 1 BG)? Thanks.

**Comment by zhiiiyang** [comment]
> I do have a follow up question @zhiiiyang. You mention that: 'Since you specified the background signature to be true, pmsignature will only return four (5 - 1 BG) signatures'.
> I would expect it to return the exact specified number of signatures, not (5 - 1 BG)... Therefore, why is it returning (5 - 1 BG)? Thanks.

Because the background signature has been estimated by using the `readBGFile` function applied to `G`. 
```
BG_prob <- readBGFile(G)
Param <- getPMSignature(G, K = 5, BG = BG_prob)
```
So, basically, BG_prob is the background signature calculated ahead of  `getPMSignature` function, which leaves the number of signatures to be 5 -1 = 4. If you are still very confused, here is the source code on this step (https://github.com/friend1ws/pmsignature/blob/bab8fcbb2291cc20c7cd02d25c1f2408ed300410/R/getSignature.R)

```
  if (!is.null(BG)) {
    isBG <- TRUE
    varK <- K - 1
  } else {
    isBG <- FALSE
    varK <- K
    BG <- 0
  }
```
What it means that varK, the number of signature, reduces by 1 if BG is not null.

**Comment by antoine186** [comment]
@zhiiiyang that is very clear. I am going to close this now. Thanks!
